server:
  port: 9000

spring:
  rabbitmq:
    host: 172.19.41.42
    port: 5672
    username: guest
    password: guest

zuul:
  routes:
    order-service: /order/**
    product-service: /product/**
  ignored-patterns:
    - /*-service/**
  sensitive-headers:
    -
