server:
  port: 9000

spring:
  rabbitmq:
    host: 172.19.41.42
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://172.19.41.42:8761/eureka/

zuul:
  routes:
    order-service: /order/**
    product-service: /product/**
  ignored-patterns:
    - /*-service/**
  sensitive-headers:
    -
