server:
  port: 8781

eureka:
  client:
    service-url:
      defaultZone: http://172.19.41.42:8761/eureka/

spring:
  rabbitmq:
    host: 172.19.41.42
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 172.19.41.42
    port: 6379
    timeout: 1000
  zipkin:
    base-url: http://172.19.41.42:9411/
  sleuth:
    sampler:
      probability: 1

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

management:
  endpoints:
    web:
      exposure:
        include: "*"

env: test
