server:
  port: 8771

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://192.168.200.136:9411/
    sleuth:
      sampler:
        probability: 1
  rabbitmq:
    host: 192.168.200.136
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

env: test2022
