server:
  port: 8771

spring:
  zipkin:
    base-url: http://172.19.41.42:9411/
    sleuth:
      sampler:
        probability: 1
  rabbitmq:
    host: 172.19.41.42
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

env: test2024
