server:
  port: 8771

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://192.168.200.131:9411/
    sleuth:
      sampler:
        probability: 1
